name: cnc_opticut
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.3.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_math_fork: ^0.7.2
  path_provider: ^2.1.2
  path: ^1.9.0
  package_info_plus: ^5.0.1
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  riverpod_lint: ^2.3.9
  image_picker: ^1.0.7
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/materials/
    - assets/images/machines/
    - assets/images/tools/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: CNCOpticut
      fonts:
        - asset: assets/fonts/CNCOpticut.ttf
