name: cnc_opticut
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'

isar_version: &isar_version 3.1.3


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.2.2
  flutter_math_fork: ^0.7.2
  isar:
    version: *isar_version
    hosted: https://isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://isar-community.dev/
  path_provider: ^2.1.2
  path: ^1.9.0
  package_info_plus: ^5.0.1
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  riverpod_lint: ^2.3.9
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  isar_generator:
    version: *isar_version
    hosted: https://isar-community.dev/

  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
