// Flutter icons CNCOpticut
// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
//
// To use this font, place it in your fonts/ directory and include the
// following in your pubspec.yaml
//
// flutter:
//   fonts:
//    - family:  CNCOpticut
//      fonts:
//       - asset: fonts/CNCOpticut.ttf
//

import 'package:flutter/widgets.dart';

class CNCOpticutIcons {
  CNCOpticutIcons._();

  static const _kFontFam = 'CNCOpticut';
  static const String? _kFontPkg = null;

  static const IconData cnc =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cutterTool =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
